
import { useApiKey } from "@/hooks/useApiKey";
import { use3DGeneration } from "@/hooks/use3DGeneration";
import ApiStatus from "@/components/ApiStatus";
import ViewerControls from "@/components/ViewerControls";
import ThreeDCanvas from "@/components/ThreeDCanvas";
import ModelInfo from "@/components/ModelInfo";

interface ModelViewer3DProps {
  uploadedImages?: File[];
}

const ModelViewer3D = ({ uploadedImages = [] }: ModelViewer3DProps) => {
  const {
    apiKey,
    setApiKey,
    showApiInput,
    setShowApiInput,
    updateApiKey,
    showApiKeyInput,
  } = useApiKey();

  const {
    isLoading,
    hasModel,
    generationStatus,
    processedImages,
  } = use3DGeneration({
    apiKey,
    showApiKeyInput,
    uploadedImages,
  });

  const resetView = () => {
    console.log("Reset view");
  };

  const downloadOBJ = () => {
    // Simulate OBJ file download with enhanced content
    const objContent = `# 3D Model - Generated by PowerPrint AI using Trellis Pipeline
# Format: OBJ (Wavefront)
# Generated from: ${uploadedImages.map(img => img.name).join(', ')}
# Vertices: 8947
# Faces: 6243
# Textures: ${processedImages.length}
# Export Date: ${new Date().toISOString()}

# This would contain actual 3D mesh data in a real implementation
# Generated using advanced image-to-3D conversion algorithms
# Optimized for 3D printing and visualization
`;
    
    const blob = new Blob([objContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'trellis_generated_3d_model.obj';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    console.log("Enhanced 3D model file downloaded");
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-white">3D Model Viewer</h2>
          <p className="text-sm text-gray-300">
            AI-Powered Image to 3D Conversion • Trellis Pipeline
          </p>
        </div>
        
        <ViewerControls
          hasModel={hasModel}
          uploadedImages={uploadedImages}
          onResetView={resetView}
          onDownloadOBJ={downloadOBJ}
        />
      </div>

      <ApiStatus
        showApiInput={showApiInput}
        apiKey={apiKey}
        setApiKey={setApiKey}
        updateApiKey={updateApiKey}
        setShowApiInput={setShowApiInput}
      />

      <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
        <div className="aspect-video bg-black relative">
          <ThreeDCanvas
            isLoading={isLoading}
            generationStatus={generationStatus}
            uploadedImages={uploadedImages}
            processedImages={processedImages}
          />
        </div>

        <ModelInfo uploadedImages={uploadedImages} />
      </div>

      <div className="text-xs text-gray-600 space-y-1">
        <p>• Powered by Trellis Image-to-3D Pipeline • Supports JPG, PNG images • Free tier: 500 credits/month</p>
        <p>• Advanced depth estimation • Texture mapping • Export formats: PLY, STL, OBJ, GLB</p>
      </div>
    </div>
  );
};

export default ModelViewer3D;
