
import { useApiKey } from "@/hooks/useApiKey";
import { use3DGeneration } from "@/hooks/use3DGeneration";
import ApiStatus from "@/components/ApiStatus";
import ViewerControls from "@/components/ViewerControls";
import ThreeDCanvas from "@/components/ThreeDCanvas";
import ModelInfo from "@/components/ModelInfo";

interface ModelViewer3DProps {
  uploadedImages?: File[];
}

const ModelViewer3D = ({ uploadedImages = [] }: ModelViewer3DProps) => {
  const {
    apiKey,
    setApiKey,
    showApiInput,
    setShowApiInput,
    updateApiKey,
    showApiKeyInput,
  } = useApiKey();

  const {
    isLoading,
    hasModel,
    generationStatus,
  } = use3DGeneration({
    apiKey,
    showApiKeyInput,
    uploadedImages,
  });

  const resetView = () => {
    console.log("Reset view");
  };

  const downloadOBJ = () => {
    // Simulate OBJ file download
    const objContent = `# 3D Model - Generated by PowerPrint AI
# Format: OBJ (Wavefront)
# Vertices: 4892
# Faces: 3247
# OBJ Format Export

# This would be actual OBJ data in a real file
# OBJ files contain vertex and face definitions
`;
    
    const blob = new Blob([objContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'generated_3d_model.obj';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    console.log("OBJ file downloaded");
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-white">3D Model Viewer</h2>
          <p className="text-sm text-gray-300">
            AI-Powered Image to 3D Conversion
          </p>
        </div>
        
        <ViewerControls
          hasModel={hasModel}
          uploadedImages={uploadedImages}
          onResetView={resetView}
          onDownloadOBJ={downloadOBJ}
        />
      </div>

      <ApiStatus
        showApiInput={showApiInput}
        apiKey={apiKey}
        setApiKey={setApiKey}
        updateApiKey={updateApiKey}
        setShowApiInput={setShowApiInput}
      />

      <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
        <div className="aspect-video bg-black relative">
          <ThreeDCanvas
            isLoading={isLoading}
            generationStatus={generationStatus}
            uploadedImages={uploadedImages}
          />
        </div>

        <ModelInfo uploadedImages={uploadedImages} />
      </div>

      <div className="text-xs text-gray-600 space-y-1">
        <p>• Powered by PowerPrint AI • Supports JPG, PNG images • Free tier: 500 credits/month</p>
        <p>• Generation time: 1-3 minutes • Export formats: PLY, STL, OBJ</p>
      </div>
    </div>
  );
};

export default ModelViewer3D;
